#!/bin/bash
set -e

source /script/common

banner "simple build image"

function assert_var_presence {
    var=$1
    if  [ -z "${!var}" ]; then
        echo "$var not set, this is required to push and deploy successfully"
        exit 1
    fi
}

for var in GCLOUD_CREDENTIALS NAMESPACE CLUSTER; do
    assert_var_presence $var
done

export REGISTRY_URL=${REGISTRY_URL:-gcr.io/celo-testnet}

# github environment var compatibility
export NAME=$(cut -d "/" -f2 <<< $GITHUB_REPOSITORY)
export COMMITSH=${COMMITSH:-$GITHUB_SHA}
export RELEASE_NAME="${NAMESPACE}-${NAME}"

source /script/credentials

# assert build environment variables
banner "Build Env Variables"
env

source /script/docker
source /script/push
source /script/manifests
source /script/deploy
source /script/notify

banner "Cleaning up"

# forcefully remove credentials, container should be destroyed but let's assert these are not persisted
gcloud auth revoke
rm ~/.config/gcloud/access_tokens.db
rm ~/.config/gcloud/credentials.db

# remove generated manifests
rm -fr /tmp/*