#!/bin/bash
set -e

if  [ -v "$GCLOUD_CREDENTIALS" ]; then
    echo "GCLOUD_CREDENTIALS not set, this is required to push and deploy successfully"
    exit 1
fi

export REGISTRY_URL=${REGISTRY_URL:-gcr.io/celo-testnet}

# github compatibility
export NAME=$(cut -d "/" -f2 <<< $GITHUB_REPOSITORY)
export COMMITSH=${COMMITSH:-GITHUB_SHA}
export RELEASE_NAME="${NAMESPACE}-${NAME}"

source /script/credentials
source /script/docker
source /script/push
source /script/manifests
source /script/deploy