#!/bin/bash
set -e

echo $GCLOUD_CREDENTIALS >> /tmp/gcloud
gcloud auth activate-service-account --key-file=/tmp/gcloud

rm /tmp/gcloud
unset GCLOUD_CREDENTIALS

# confirm overwriting docker config.json
yes | gcloud auth configure-docker

# get cluster credentials, also sets k8s context as side effect
gcloud container clusters get-credentials --project=${PROJECT:-celo-testnet} --zone=${ZONE:-us-west1-a} ${CLUSTER:-celo-networks-dev}