#!/bin/bash
set -ex

echo $GCLOUD_CREDENTIALS >> /tmp/gcloud
gcloud auth activate-service-account --key-file=/tmp/gcloud
rm /tmp/gcloud

# confirm overwriting docker config.json
yes | gcloud auth configure-docker