#!/bin/bash
set -e

CHARTDIR=${CHARTDIR:-ops/helm}
MANIFESTS_DIR=${MANIFESTS_DIR:-/tmp/manifests}

rm -rf ${MANIFESTS_DIR}
mkdir -p ${MANIFESTS_DIR}

if [[ -f "${CHARTDIR}/values.yaml" ]]; then
	defaults_args="--values ${CHARTDIR}/values.yaml"
fi

if [[ -f "${CHARTDIR}/values/${NAMESPACE:?}.yaml" ]]; then
	namespace_args="--values ${CHARTDIR}/values/${NAMESPACE:?}.yaml"
fi

helm template ${RELEASE_NAME} ${CHARTDIR} \
	${defaults_args} \
	--set image.tag="${COMMITSH}" \
	${namespace_yaml} \
	--output-dir ${MANIFESTS_DIR}
