#!/bin/bash

#source /script/common

#banner "Notify"

REPO=${GITHUB_REPOSITORY:-something}
SHORT_HASH=$(echo $COMMITSH | cut -c1-8)
URL="https://github.com/$REPO/commit/$COMMITSH"
USER=${GITHUB_ACTOR:-someone}
TOPIC=${PUBSUB_TOPIC:-seal_abs}

content="{\"user\":\"$USER\", \"repo\":\"$REPO\", \"version\":\"$COMMITSH\",\"cluster\":\"$CLUSTER\", \"namespace\":\"$NAMESPACE\"}"
message="{ \"source\":\"sbi\", \"tags\":[\"deployment\", \"$REPO\"], \"content\":$content  }"

gcloud pubsub topics publish ${TOPIC} --project=${PROJECT} --message="${message}"