#!/bin/bash
set -e

source ./common

banner "Push container to registry"

ECHO=""

if [ -n "$DRY_RUN" ]; then
    ECHO="echo"
fi

${ECHO} docker push ${REGISTRY_URL:?}/${NAME:?}:${COMMITSH:?}
${ECHO} docker push ${REGISTRY_URL:?}/${NAME:?}:latest